image: docker:24.0.7

services:
  - docker:24.0.7-dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build_image
  - build
  - test

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_docker_image:
  stage: build_image
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

build:
  stage: build
  script:
    - docker pull $IMAGE_TAG
    - docker run --name maven_build $IMAGE_TAG mvn compile

test:
  stage: test
  script:
    - docker pull $IMAGE_TAG
    - docker run --name maven_test $IMAGE_TAG mvn test

cache:
  paths:
    - .m2/repository