image: docker:24.0.7

services:
  - name: docker:24.0.7-dind
    alias: docker

variables:
  DOCKER_DRIVER: overlay2
  BASE_IMAGE_TAG: $CI_REGISTRY_IMAGE/base-maven-jdk-21:latest
  APP_IMAGE_TAG: $CI_REGISTRY_IMAGE/my-app:latest

stages:
  - build_base_image
  - build_image
  - test
  - deploy

build_base_image:
  stage: build_base_image
  script:
    - echo "Checking if the base Docker image already exists..."
    - if docker pull "$BASE_IMAGE_TAG"; then
      echo "Base image found in registry. Skipping build...";
      else
      echo "Base image not found. Building the base Docker image...";
      docker build -f Dockerfile.base -t "$BASE_IMAGE_TAG" .
      echo "Pushing the base image to the registry...";
      docker push "$BASE_IMAGE_TAG";
      fi
  only:
    - schedules

build_image:
  stage: build_image
  script:
    - echo "Building the Docker image..."
    - docker build -t "$APP_IMAGE_TAG" .
    - echo "Pushing the app image to the registry..."
    - docker push "$APP_IMAGE_TAG"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

test:
  stage: test
  image: $BASE_IMAGE_TAG
  script:
    - echo "Running tests..."
    - mvn test

deploy:
  stage: deploy
  image: docker:24.0.7
  script:
    - echo "Deploying the application..."
    - docker pull "$APP_IMAGE_TAG"
    - docker stop my-app-container || true
    - docker rm my-app-container || true
    - docker run -d -p 8080:8080 --name my-app-container "$APP_IMAGE_TAG"
  only:
    - main
  tags:
    - production
