image: docker:24.0.7

services:
  - docker:24.0.7-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE/maven-jdk-21:latest

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

build:
  stage: build
  script:
    - docker pull $IMAGE_TAG
    - docker run --rm -v $(pwd):/app -w /app $IMAGE_TAG mvn compile

test:
  stage: test
  script:
    - docker pull $IMAGE_TAG
    - docker run --rm -v $(pwd):/app -w /app $IMAGE_TAG mvn test

# Add deploy stage if needed
# deploy:
#   stage: deploy
#   script:
#     - deployment scripts here
