image: docker:24.0.7-dind

services:
  - docker:24.0.7-dind

variables:
  DOCKER_DRIVER: overlay2
  # Define the image tag, and use the CI_REGISTRY_IMAGE variable for the repository path
  IMAGE_TAG: $CI_REGISTRY_IMAGE/maven-jdk-21:latest

stages:
  - build_image
  - build
  - test

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build_image
  script:
    - docker build --pull -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

build:
  stage: build
  image: "$IMAGE_TAG"
  script:
    - mvn compile

test:
  stage: test
  image: "$IMAGE_TAG"
  script:
    - mvn test
