image: docker:24.0.7

services:
  - name: docker:24.0.7-dind
    alias: docker

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE/maven-jdk-21:latest

stages:
  - build_image
  - test
  - deploy

build_image:
  stage: build_image
  before_script:
    - if [ -z $(docker images -q $IMAGE_TAG) ]; then
      echo "Logging into GitLab Registry...";
      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY;
      fi
  script:
    - echo "Building the Docker image..."
    - docker build -t "$IMAGE_TAG" .
    - echo "Pushing the image to the registry..."
    - docker push "$IMAGE_TAG"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

test:
  stage: test
  image: maven:3.9.5-eclipse-temurin-21-alpine
  script:
    - echo "Running tests..."
    - mvn test

deploy:
  stage: deploy
  image: docker:24.0.7
  before_script:
    - docker info
  script:
    - echo "Deploying the application..."
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker pull "$IMAGE_TAG" || true
    - docker stop elektrihind-app-container || true
    - docker rm elektrihind-app-container || true
    - docker run -d -p 8080:8080 --restart always --name elektrihind-app-container -e TELEGRAM_ELEKTRITEEMU_TOKEN="$TELEGRAM_ELEKTRITEEMU_TOKEN" -e TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN" -e OMDB_API_KEY="$OMDB_API_KEY" "$IMAGE_TAG"
  only:
    - main
  tags:
    - production
