image: docker:24.0.7

services:
  - name: docker:24.0.7-dind
    alias: docker

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE/my-app:latest

stages:
  - build_and_test
  - deploy

build_image:
  stage: build_and_test
  before_script:
    - echo "Logging into GitLab Registry..."
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "Building the Docker image..."
    - docker build -t "$IMAGE_TAG" .
    - echo "Pushing the image to the registry..."
    - docker push "$IMAGE_TAG"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

test:
  stage: build_and_test
  image: maven:3.9-eclipse-temurin-21-alpine
  script:
    - echo "Running tests and SonarCloud analysis..."
    #    - mvn -T 1C --batch-mode clean verify sonar:sonar -Dsonar.projectKey=ktenman_elektrihind -Dsonar.organization=ktenman -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
    - mvn -T 1C --batch-mode test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml

deploy:
  stage: deploy
  image: docker:24.0.7
  before_script:
    - echo "Logging into GitLab Registry..."
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "Creating temporary .env file..."
    - echo TELEGRAM_ELEKTRITEEMU_TOKEN="$TELEGRAM_ELEKTRITEEMU_TOKEN" > .env
    - echo TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN" >> .env
    - echo OMDB_API_KEY="$OMDB_API_KEY" >> .env
    - echo "Deploying the application using Docker Compose..."
    - docker-compose pull || true
    - docker ps --filter "publish=8080" -q | xargs -r docker rm -f || true
    - docker-compose down --rmi all -v || true
    - docker-compose down --remove-orphans || true
    - docker-compose up -d
    - echo "Pruning unused Docker images..."
    - docker image prune -af
    - echo "Cleaning up temporary files..."
    - rm .env
  only:
    - main
  tags:
    - production

