stages:
  - build_image
  - deploy_image

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/my-maven-app:latest

# Define the job to build and push the Docker image
build_image:
  stage: build_image
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  script:
    - echo "Building Docker image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main

# Define the job to run the application using the built Docker image
deploy_image:
  stage: deploy_image
  image: $IMAGE_TAG
  script:
    - echo "Running application..."
    - >
      if [ -z "$CI_COMMIT_TAG" ]; then
        echo "Running a non-tagged build, not deploying";
      else
        java $JAVA_OPTS -jar /app/app.jar
      fi
  only:
    - tags