image: docker:24.0.7

services:
  - docker:24.0.7-dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE/maven-jdk-21:latest
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - diagnostics
  - build_image
  - build
  - test

diagnostics:
  stage: diagnostics
  script:
    - echo "Checking Docker version..."
    - docker --version || true
    - echo "Checking which Docker..."
    - which docker || true
    - echo "Checking PATH..."
    - echo $PATH
    - echo "Checking user permissions..."
    - id
    - echo "Checking if Docker service is up..."
    - ps aux | grep docker || true

before_script:
  - echo "Waiting for Docker to start..."
  - sleep 10
  - echo "Logging into GitLab Registry..."
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build_image
  script:
    - echo "Building the Docker image..."
    - docker build --pull -t "$IMAGE_TAG" .
    - echo "Pushing the image to the registry..."
    - docker push "$IMAGE_TAG"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

build:
  stage: build
  image: "$IMAGE_TAG"
  services: []
  before_script:
    - echo "Installing Docker client..."
    - apt-get update -y && apt-get install -y docker.io
    - echo "Logging into GitLab Registry within the build image..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "Compiling the project..."
    - mvn compile
    - echo "Listing contents of the Maven repository to ensure it's populated..."
    - ls -la ~/.m2/repository/ || true

test:
  stage: test
  image: "$IMAGE_TAG"
  services: []
  script:
    - echo "Running tests..."
    - mvn test
