version: '3.8'
services:
  elektrihind-app:
    container_name: elektrihind_main
    image: ktenman/elektrihind:latest
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_ELEKTRITEEMU_TOKEN=${TELEGRAM_ELEKTRITEEMU_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - TWO_CAPTCHA_API_KEY=${TWO_CAPTCHA_API_KEY}
      - DIGITAL_OCEAN_API_TOKEN=${DIGITAL_OCEAN_API_TOKEN}
    volumes:
      - cache-volume:/app/cache
    restart: always

volumes:
  cache-volume:
