version: '3.8'
services:
  elektrihind-app:
    container_name: elektrihind_main
    image: ktenman/elektrihind:latest
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_ELEKTRITEEMU_TOKEN=${TELEGRAM_ELEKTRITEEMU_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - TWO_CAPTCHA_API_KEY=${TWO_CAPTCHA_API_KEY}
      - DIGITAL_OCEAN_API_TOKEN=${DIGITAL_OCEAN_API_TOKEN}
      - SCRAPENINJA_API_KEY=${SCRAPENINJA_API_KEY}
      - VISION_BASE64_ENCODED_KEY=${VISION_BASE64_ENCODED_KEY}
      - OPENAI_API_TOKEN=${OPENAI_API_TOKEN}
    volumes:
      - cache-volume:/app/cache
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes # This enables AOF persistence
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  cache-volume:
  redis-data:

networks:
  mynetwork:
