version: '3.8'
services:
  elektrihind-app:
    container_name: elektrihind_main
    image: ktenman/elektrihind:latest
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_ELEKTRITEEMU_TOKEN=${TELEGRAM_ELEKTRITEEMU_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - TWO_CAPTCHA_API_KEY=${TWO_CAPTCHA_API_KEY}
      - DIGITAL_OCEAN_API_TOKEN=${DIGITAL_OCEAN_API_TOKEN}
      - SCRAPENINJA_API_KEY=${SCRAPENINJA_API_KEY}
    volumes:
      - cache-volume:/app/cache
    restart: always
  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes # This enables AOF persistence
    restart: always

volumes:
  cache-volume:
  redis-data:

networks:
  mynetwork:
