version: '3.8'
services:
  elektrihind-app:
    image: ktenman/elektrihind:latest
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_ELEKTRITEEMU_TOKEN=${TELEGRAM_ELEKTRITEEMU_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OMDB_API_KEY=${OMDB_API_KEY}
    volumes:
      - cache-volume:/app/cache
    restart: always

volumes:
  cache-volume:
