telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  monitoringChatId: -1001645546677
  privateChatId: 116578187
  elektriteemu:
    token: ${TELEGRAM_ELEKTRITEEMU_TOKEN}
    username: ElektriTeemu

electricity-prices-api:
  url: https://elektrihind.ee/api

omdb-api:
  url: http://www.omdbapi.com
  key: ${OMDB_API_KEY}

twocaptcha:
  key: ${TWO_CAPTCHA_API_KEY}

scrapeninja:
  key: ${SCRAPENINJA_API_KEY}

imdb-api:
  url: https://imdb-api.projects.thetuhin.com

digitalocean:
  token: ${DIGITAL_OCEAN_API_TOKEN}

app.messaging.type: redis

spring:
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    function:
      definition: rabbitmqPublisher;rabbitmqConsumer
    stream:
      bindings:
        rabbitmqPublisher-out-0:
          destination: picture-request-queue
        rabbitmqConsumer-in-0:
          destination: picture-response-queue

vision:
  base64EncodedKey: ${VISION_BASE64_ENCODED_KEY}

openai:
  token: ${OPENAI_API_TOKEN}

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: WARN
    ee:
      tenman:
        elektrihind: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSZ,Europe/Tallinn} [%thread] %-5level %logger{36} [UUID: %X{uuid}] - %msg%n'

