telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  monitoringChatId: -1001645546677
  privateChatId: 116578187
  elektriteemu:
    token: ${TELEGRAM_ELEKTRITEEMU_TOKEN}
    username: ElektriTeemu

electricity-prices-api:
  url: https://elektrihind.ee/api

omdb-api:
  url: http://www.omdbapi.com
  key: ${OMDB_API_KEY}

twocaptcha:
  key: ${TWO_CAPTCHA_API_KEY}

imdb-api:
  url: https://imdb-api.projects.thetuhin.com

digitalocean:
  api:
    token: ${DIGITAL_OCEAN_API_TOKEN}

spring:
  data:
    redis:
      host: localhost
      port: 6379
