name: Java CI with Docker

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ktenman/elektrihind
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Test with Maven
        run: mvn -T 1C --batch-mode test

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          ssh githubuser@tenman.ee 'docker pull "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" || true'
          ssh githubuser@tenman.ee 'docker stop my-container || true'
          ssh githubuser@tenman.ee 'docker rm my-container || true'
          ssh githubuser@tenman.ee 'docker run -d -p 8080:8080 --restart always --name my-container "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"'
