name: Java CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven, Run Sonar Analysis, and OWASP Dependency Check
        run: |
          mvn -T 1C --batch-mode clean install sonar:sonar org.owasp:dependency-check-maven:check -X \
            -Dsonar.projectKey=ktenman_elektrihind \
            -Dsonar.organization=ktenman \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
