name: Java CI with Docker

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ktenman/elektrihind
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21-alpine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - run: mvn -T 1C --batch-mode test

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - run: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
      - run: docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: [ test, build_and_push ]
    steps:
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key of tenman.ee to known hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - run: |
          ssh githubuser@tenman.ee 'docker pull "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" || true'
          ssh githubuser@tenman.ee 'docker stop my-container || true'
          ssh githubuser@tenman.ee 'docker rm my-container || true'
          ssh githubuser@tenman.ee 'docker run -d -p 8080:8080 --restart always --name my-container "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"'
